"""empty message

Revision ID: c21918620f4f
Revises: 7f19332282b9
Create Date: 2020-05-21 13:39:19.563297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21918620f4f'
down_revision = '7f19332282b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE todo SET completed=False WHERE completed IS NULL;')

    op.alter_column('todo','completed',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
